### PR TITLE
Bugfix for 38

### PR DESCRIPTION
**Pull request by javiersalcedopuyo**
Fix for the issue #38 

I replaced [NFD](https://github.com/saurvs/nfd-rs) with [TinyFileDialogs](https://github.com/jdm/tinyfiledialogs-rs)
This fixed the issue and allowed exporting again.
However, at the moment I only have my MacBook available, so I couldn't test it in other platforms.

### CODE REVIEW

**Comment by zakorgy** [comment]
Hello again @javiersalcedopuyo :) . Thanks for hunting down this. I can test this on other platforms, and check if it works on Windows and Linux.

**Comment by zakorgy** [comment]
I've tested it on Linux and Windows, and it works. Thanks @javiersalcedopuyo

**Comment by javiersalcedopuyo** [comment]
@zakorgy could you add the hacktoberfest-accepted label please? I only need 1 more PR 😅

**Comment by zakorgy** [comment]
Sure :smiley: I've added the label.

**Pull request merged**
